### ISSUE TITLE
Proposal: splitting `pub` and `flutter`

### ISSUE THREAD

**Issue by jack-r-warren** [google/mono_repo.dart#167] opened 2019-06-04 00:02 UTC
In working on #166 it became apparent to me that there's a number of cases where you'd want to run a command on all of the Flutter or non-Flutter packages. I can also imagine a number of other dependency-related tasks like #117. The following would be a breaking change but would allow room to grow:
- `mono_repo pub`: argument pass-through to `pub` executable, run on all non-flutter packages
- `mono_repo flutter`: argument pass-through to `flutter` executable, run on all flutter packages
- `mono_repo dependency` (abbreviation `dep`?)
  - `get`: do `pub get` or `flutter packages get` across all packages as needed
  - `upgrade`: same for upgrade
  - `override [add|remove]`: add or remove sibling overrides (#117)

The change would be breaking for anyone currently using `mono_repo pub [get|upgrade]` to work with Flutter dependencies. It might make sense paired with #145 in a major version bump.

**Comment by kevmoo** [comment] 2021-11-25 04:51
Closing as duplicate of https://github.com/google/mono_repo.dart/issues/45

**Closed by kevmoo** 2021-11-25 04:51 UTC
