### ISSUE TITLE
Flutter Support in Github Actions

### ISSUE THREAD

**Issue by mark-dropbear** [google/mono_repo.dart#375] opened 2022-04-08 16:20 UTC
I have a quick question that I wasn't sure if I was doing something wrong or this was a known issue.

I have a mixed repository (https://github.com/dropbear-software/fullstack-dart-demo) that contains:

1. A Dart Package
2. A Dart CLI application
3. A Flutter Web application

I'm using `mono_repo` to mange all of this and when I run `mono_repo presubmit` everything works find but on Github Actions it fails because it is downloading the Dart SDK rather than the Flutter SDK and when it comes to run `dart pub upgrade` it will fail as can be seen here https://github.com/dropbear-software/fullstack-dart-demo/runs/5871740230?check_suite_focus=true

I just wanted to get a quick understanding if this was something that could be easily fixed on my end or it isn't a supported use case at the moment.

**Comment by jakemac53** [comment] 2022-04-08 17:19
We do have an example flutter project in this repo and it seems to work without anything special as far as I can tell. Have you tried upgrading `mono_repo` to the latest version?

**Comment by jakemac53** [comment] 2022-04-08 17:22
I think there is a bug where it is grouping analyze steps that it thinks are identical into a single job - but it needs to separate them based on the SDK they use.

**Comment by jakemac53** [comment] 2022-04-08 17:23
cc @kevmoo

**Comment by mark-dropbear** [comment] 2022-04-08 17:49
Thanks for the reply @jakemac53 I made the upgrade from 6.1.0 to 6.2.0 and reran `mono_repo check && mono_repo generate` both of which again worked locally but fail for the same reason as previously in GitHub Actions https://github.com/dropbear-software/fullstack-dart-demo/runs/5889388138?check_suite_focus=true

Let me also dive into how you have things set up in this repo for the flutter application because if thats the case I would have to assume that it is possible for me also. All I can tell is that it uses the `dart-lang/setup-dart@v1.3` action and therefore I would have to assume that it never has a chance of ever working because it will always be executing in a purely Dart based SDK environment.

Maybe @kevmoo has some ideas in the meantime as well, lets see :)

**Comment by jakemac53** [comment] 2022-04-08 17:56
I have confirmed the issue is that `analyze` actions will get merged based on the Name of the action (analyze) and the command (which is just `dart analyze`). So it doesn't distinguish between dart/flutter and the flutter command ends up getting grouped in with dart analyze actions (but won't get the proper flutter setup).

So it is a bug. You can likely remove any `merge_stages` config that you have set up in your `mono_repo.yaml` to resolve this issue for now.

**Comment by jakemac53** [comment] 2022-04-08 17:57
One solution is to use `flutter analyze` instead of `dart analyze`. Although we might want a more general solution to this problem.

**Comment by mark-dropbear** [comment] 2022-04-08 18:01
Appreciate the help in the meantime!

**Closed** 2022-04-12 19:16 UTC

**Comment by jakemac53** [comment] 2022-04-12 19:19
This is published now as version 6.2.1, please re-open if it doesn't resolve things
